#!/usr/bin/env bun
//! Sample corpus: real installers, too large for git.
//!
//! `corpus.toml` lives in the repo, so a checkout knows the whole corpus without touching the
//! network. Object storage holds only content-addressed blobs.

import { readdir, mkdir, unlink } from "node:fs/promises";
import { basename, join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const MANIFEST = join(ROOT, "corpus.toml");
const SAMPLES = process.env.COOKFS_CORPUS_DIR ?? join(ROOT, "samples");
const JOBS = Number(process.env.COOKFS_CORPUS_JOBS ?? 8);

const WINDOW = 4 << 20;

/// Exceeds any sample, forcing one PUT per blob. Concurrent multipart uploads deadlock: past
/// one, their in-flight parts exhaust the connection pool and none can complete.
const PART = 1024 << 20;

type Format = "CFS0002" | "CFS0003" | "none";

/// How to reach the archive: `raw` is the file itself, `zip` wraps it in a macOS `.app` bundle.
type Container = "raw" | "zip";

type Sample = {
  name: string;
  sha256: string;
  size: number;
  format: Format;
  container: Container;
  tags: string[];
};

function die(message: string): never {
  console.error(`corpus: ${message}`);
  process.exit(1);
}

function human(bytes: number): string {
  const units = ["B", "KiB", "MiB", "GiB"];
  let n = bytes;
  let u = 0;
  while (n >= 1024 && u < units.length - 1) {
    n /= 1024;
    u += 1;
  }
  return `${u === 0 ? n : n.toFixed(1)} ${units[u]}`;
}

async function pool<T, R>(items: T[], limit: number, fn: (item: T) => Promise<R>): Promise<R[]> {
  const out = new Array<R>(items.length);
  let next = 0;
  await Promise.all(
    Array.from({ length: Math.min(limit, items.length) }, async () => {
      for (let i = next++; i < items.length; i = next++) out[i] = await fn(items[i]!);
    }),
  );
  return out;
}

function bucket(): Bun.S3Client {
  const missing = [
    "S3_ENDPOINT",
    "S3_BUCKET",
    "S3_ACCESS_KEY_ID",
    "S3_SECRET_ACCESS_KEY",
  ].filter((key) => !process.env[key]);
  if (missing.length > 0) die(`no credentials: ${missing.join(", ")} unset`);

  return new Bun.S3Client({
    endpoint: process.env.S3_ENDPOINT,
    bucket: process.env.S3_BUCKET,
    accessKeyId: process.env.S3_ACCESS_KEY_ID,
    secretAccessKey: process.env.S3_SECRET_ACCESS_KEY,
    region: "auto",
  });
}

const key = (sha256: string) => `blobs/${sha256}`;

async function load(): Promise<Sample[]> {
  const file = Bun.file(MANIFEST);
  if (!(await file.exists())) return [];
  const parsed = Bun.TOML.parse(await file.text()) as { sample?: Sample[] };
  return (parsed.sample ?? []).map((s) => ({ ...s, tags: s.tags ?? [] }));
}

/// Hand-rolled, not `Bun.TOML.stringify`: this file is reviewed as a diff, so the shape is fixed.
async function save(samples: Sample[]): Promise<void> {
  const sorted = [...samples].sort((a, b) => a.name.localeCompare(b.name));
  const total = sorted.reduce((sum, s) => sum + s.size, 0);
  const body = sorted.map(
    (s) =>
      `[[sample]]\nname = ${JSON.stringify(s.name)}\nsha256 = "${s.sha256}"\n` +
      `size = ${s.size}\nformat = "${s.format}"\ncontainer = "${s.container}"\n` +
      `tags = [${s.tags.map((t) => JSON.stringify(t)).join(", ")}]\n`,
  );
  await Bun.write(
    MANIFEST,
    `# Sample corpus, generated by tools/corpus.ts. Blobs are content-addressed in object\n` +
      `# storage; \`tempo corpus -- pull\` materializes them under samples/.\n` +
      `#\n# ${sorted.length} samples, ${human(total)}.\n\n${body.join("\n")}`,
  );
}

async function sha256(path: string): Promise<string> {
  const hasher = new Bun.CryptoHasher("sha256");
  for await (const chunk of Bun.file(path).stream()) hasher.update(chunk);
  return hasher.digest("hex");
}

function signatureIn(text: string): Format {
  const at2 = text.lastIndexOf("CFS0002");
  const at3 = text.lastIndexOf("CFS0003");
  if (at2 < 0 && at3 < 0) return "none";
  return at3 > at2 ? "CFS0003" : "CFS0002";
}

/// cookfs has no header, so the only way to identify one is to scan backward from the end.
async function sniffRaw(path: string): Promise<{ format: Format; tags: string[] }> {
  const file = Bun.file(path);
  const tags: string[] = [];
  let format: Format = "none";

  for (let end = file.size; end > 0 && format === "none"; end -= WINDOW) {
    const start = Math.max(0, end - WINDOW - 8); // overlap, so a split signature still matches
    const text = new TextDecoder("latin1").decode(await file.slice(start, end).arrayBuffer());
    format = signatureIn(text);
    if (text.includes("Inno Setup Setup Data")) tags.push("inno");
  }
  return { format, tags };
}

/// A macOS `.app.zip` deflates the installer, hiding the signature until it is expanded.
/// Streaming every member costs a little throughput and avoids parsing a zip listing.
async function sniffZip(path: string): Promise<Format> {
  const proc = Bun.spawn(["unzip", "-p", path], { stdout: "pipe", stderr: "ignore" });
  const decoder = new TextDecoder("latin1");
  let format: Format = "none";
  let carry = "";

  for await (const chunk of proc.stdout) {
    const text = carry + decoder.decode(chunk);
    const found = signatureIn(text);
    if (found !== "none") format = found;
    carry = text.slice(-8); // a signature split across two chunks still matches
  }
  proc.kill();
  return format;
}

async function isZip(path: string): Promise<boolean> {
  const head = new Uint8Array(await Bun.file(path).slice(0, 4).arrayBuffer());
  return head[0] === 0x50 && head[1] === 0x4b;
}

async function sniff(path: string): Promise<{
  format: Format;
  container: Container;
  tags: string[];
}> {
  const raw = await sniffRaw(path);
  if (raw.format === "none" && (await isZip(path))) {
    const nested = await sniffZip(path);
    if (nested !== "none") return { format: nested, container: "zip", tags: raw.tags };
  }
  return { ...raw, container: "raw" };
}

async function localFiles(): Promise<string[]> {
  try {
    const entries = await readdir(SAMPLES, { withFileTypes: true });
    return entries.filter((e) => e.isFile() && e.name !== "manifest.toml").map((e) => e.name);
  } catch {
    return [];
  }
}

function select(samples: Sample[], args: string[]): Sample[] {
  const wanted = args.filter((a) => a.startsWith("--tag=")).map((a) => a.slice(6));
  if (wanted.length === 0) return samples;
  return samples.filter((s) => wanted.some((t) => s.tags.includes(t)));
}

async function status(): Promise<void> {
  const samples = await load();
  if (samples.length === 0) die(`${MANIFEST} lists no samples`);

  const present = new Set(await localFiles());
  const tracked = new Set(samples.map((s) => s.name));

  const sized = await pool(samples, JOBS, async (s) => Bun.file(join(SAMPLES, s.name)).size);
  const missing = samples.filter((_, i) => !present.has(samples[i]!.name));
  const wrong = samples.filter((s, i) => present.has(s.name) && sized[i] !== s.size);
  const extra = [...present].filter((n) => !tracked.has(n));

  const remote = new Set<string>();
  for await (const page of listBlobs()) for (const k of page) remote.add(k);
  const unpushed = samples.filter((s) => !remote.has(key(s.sha256)));

  const bytes = samples.reduce((sum, s) => sum + s.size, 0);
  const byFormat = new Map<Format, number>();
  for (const s of samples) byFormat.set(s.format, (byFormat.get(s.format) ?? 0) + 1);

  console.log(`manifest  ${samples.length} samples, ${human(bytes)}`);
  console.log(
    `          ${[...byFormat].map(([f, n]) => `${f} ${n}`).join(", ")}`,
  );
  console.log(
    `local     ${samples.length - missing.length} present, ${missing.length} missing, ` +
      `${wrong.length} wrong size, ${extra.length} untracked`,
  );
  console.log(`remote    ${samples.length - unpushed.length} present, ${unpushed.length} missing`);

  for (const s of missing) console.log(`  missing   ${s.name}`);
  for (const s of wrong) console.log(`  wrong     ${s.name}`);
  for (const n of extra) console.log(`  untracked ${n}`);
  for (const s of unpushed) console.log(`  unpushed  ${s.name}`);
}

async function* listBlobs(): AsyncGenerator<string[]> {
  const b = bucket();
  let token: string | undefined;
  do {
    const page = await b.list({ prefix: "blobs/", maxKeys: 1000, continuationToken: token });
    yield (page.contents ?? []).map((o) => o.key);
    token = page.isTruncated ? page.nextContinuationToken : undefined;
  } while (token);
}

async function pull(args: string[]): Promise<void> {
  const samples = select(await load(), args);
  const verify = args.includes("--verify");
  await mkdir(SAMPLES, { recursive: true });

  const stale = await pool(samples, JOBS, async (s) => {
    const path = join(SAMPLES, s.name);
    const file = Bun.file(path);
    if (!(await file.exists()) || file.size !== s.size) return s;
    if (verify && (await sha256(path)) !== s.sha256) return s;
    return null;
  });

  const todo = stale.filter((s): s is Sample => s !== null);
  if (todo.length === 0) {
    console.log(`corpus up to date: ${samples.length} samples`);
    return;
  }

  const bytes = todo.reduce((sum, s) => sum + s.size, 0);
  console.log(`fetching ${todo.length} samples, ${human(bytes)}`);

  const b = bucket();
  const started = performance.now();
  await pool(todo, JOBS, async (s) => {
    const path = join(SAMPLES, s.name);
    // Hashed on the way in, so a corrupt or wrong object is caught without a second pass.
    const hasher = new Bun.CryptoHasher("sha256");
    const sink = Bun.file(path).writer();
    for await (const chunk of b.file(key(s.sha256)).stream()) {
      hasher.update(chunk);
      sink.write(chunk);
    }
    await sink.end();

    const got = hasher.digest("hex");
    if (got !== s.sha256) {
      await unlink(path);
      die(`${s.name}: expected sha256 ${s.sha256}, got ${got}`);
    }
    console.log(`  ${s.name}  ${human(s.size)}`);
  });

  const seconds = (performance.now() - started) / 1000;
  console.log(
    `fetched ${human(bytes)} in ${seconds.toFixed(1)}s (${human(bytes / seconds)}/s)`,
  );
}

async function push(): Promise<void> {
  const samples = await load();
  const remote = new Set<string>();
  for await (const page of listBlobs()) for (const k of page) remote.add(k);

  const todo = samples.filter((s) => !remote.has(key(s.sha256)));
  if (todo.length === 0) {
    console.log(`remote up to date: ${samples.length} blobs`);
    return;
  }

  const b = bucket();
  const bytes = todo.reduce((sum, s) => sum + s.size, 0);
  console.log(`uploading ${todo.length} blobs, ${human(bytes)}`);

  const started = performance.now();
  await pool(todo, JOBS, async (s) => {
    const path = join(SAMPLES, s.name);
    const file = Bun.file(path);
    if (!(await file.exists())) die(`${s.name} is in the manifest but not in ${SAMPLES}`);
    if (file.size > PART) die(`${s.name} is too large for a single upload`);
    await b.write(key(s.sha256), file, { partSize: PART });
    console.log(`  ${s.name}  ${human(s.size)}`);
  });

  const seconds = (performance.now() - started) / 1000;
  console.log(
    `uploaded ${human(bytes)} in ${seconds.toFixed(1)}s (${human(bytes / seconds)}/s)`,
  );
}

async function add(args: string[]): Promise<void> {
  const paths = args.filter((a) => !a.startsWith("--"));
  if (paths.length === 0) die("add needs at least one file");

  const samples = await load();
  const byName = new Map(samples.map((s) => [s.name, s]));
  const extra = args.filter((a) => a.startsWith("--tag=")).map((a) => a.slice(6));

  for (const path of paths) {
    const name = basename(path);
    const file = Bun.file(path);
    if (!(await file.exists())) die(`${path} does not exist`);

    const { format, container, tags } = await sniff(path);
    const entry: Sample = {
      name,
      sha256: await sha256(path),
      size: file.size,
      format,
      container,
      // Existing tags survive a re-add, so a hand-curated label is not lost to a refresh.
      tags: [...new Set([...(byName.get(name)?.tags ?? []), ...tags, ...extra])].sort(),
    };
    byName.set(name, entry);
    const label = format === "none" ? "  --   " : `${format}${container === "zip" ? "+" : " "}`;
    console.log(
      `${label} ${human(entry.size).padStart(9)}  ${name}` +
        (entry.tags.length > 0 ? `  [${entry.tags.join(" ")}]` : ""),
    );
  }

  await save([...byName.values()]);
  console.log(`${MANIFEST} now lists ${byName.size} samples`);
}

async function verify(): Promise<void> {
  const samples = await load();
  const bad: string[] = [];

  await pool(samples, JOBS, async (s) => {
    const path = join(SAMPLES, s.name);
    if (!(await Bun.file(path).exists())) {
      bad.push(`${s.name}: absent`);
      return;
    }
    const got = await sha256(path);
    if (got !== s.sha256) bad.push(`${s.name}: sha256 ${got} != ${s.sha256}`);
  });

  for (const line of bad) console.error(`  ${line}`);
  if (bad.length > 0) die(`${bad.length} of ${samples.length} samples failed`);
  console.log(`verified ${samples.length} samples`);
}

async function prune(args: string[]): Promise<void> {
  const tracked = new Set((await load()).map((s) => s.name));
  const extra = (await localFiles()).filter((n) => !tracked.has(n));
  if (extra.length === 0) {
    console.log("nothing untracked");
    return;
  }
  for (const name of extra) console.log(`  ${args.includes("--force") ? "removed" : "extra"} ${name}`);
  if (!args.includes("--force")) {
    console.log(`${extra.length} untracked files; re-run with --force to delete`);
    return;
  }
  for (const name of extra) await unlink(join(SAMPLES, name));
}

const USAGE = `corpus <command>

  status              compare manifest, samples/, and object storage
  pull [--tag=T]      download missing or wrong-sized samples  [--verify rehashes present ones]
  push                upload blobs the remote does not have
  add <file>...       hash, sniff, and record files  [--tag=T adds a label]
  verify              rehash every local sample against the manifest
  prune [--force]     report, then delete, samples the manifest does not list`;

const [command = "status", ...rest] = process.argv.slice(2);
switch (command) {
  case "status":
    await status();
    break;
  case "pull":
    await pull(rest);
    break;
  case "push":
    await push();
    break;
  case "add":
    await add(rest);
    break;
  case "verify":
    await verify();
    break;
  case "prune":
    await prune(rest);
    break;
  default:
    console.log(USAGE);
    process.exit(command === "help" || command === "--help" ? 0 : 1);
}
